import Head from 'next/head';
import { ReactElement } from 'react';
import { Layout } from '@components/Layout';
// import { useTheme } from "next-themes";

const Home = () => {
  // const { theme, setTheme } = useTheme();
  // const toggleTheme = () => setTheme(theme === "light" ? "dark" : "light");
  return (
    <>
      <Head>
        <title>Andrew Crescencio&apos;s blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          display: 'grid',
          placeContent: 'center',
          minHeight: '100vh',
          textAlign: 'center',
        }}
      >
        <h1 style={{ fontSize: '24px', marginBottom: '14px' }}>
          🚧 Em construção 🚧
        </h1>
        <h2 style={{ fontSize: '18px', marginBottom: '34px' }}>
          veja a versão 1.0{' '}
          <a
            href="https://andrewcrescencio-blog.vercel.app"
            target="_blank"
            rel="noreferrer"
          >
            aqui
          </a>
        </h2>
        <p style={{ fontSize: '14px', marginBottom: '8px' }}>
          O que estou fazendo no momento?
        </p>
        <p style={{ fontSize: '14px', marginBottom: '8px' }}>
          criando componentes
        </p>
      </main>
    </>
  );
};
Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
